version: '3.8'

services:
    app:
        command: sh -c "npm ci && npm run build && sleep infinity"
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-app
        image: node:16
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        volumes:
            - .:/app
        working_dir: /app
    nginx:
        build:
            context: .
            dockerfile: ${DOCKER_COMPOSE__SERVICES_PATH}/nginx/Dockerfile
        command: sh -c "service nginx restart && sleep infinity"
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-nginx
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        ports:
            - 127.0.0.2:80:80
            - 443:443
        volumes:
            - ./test:/var/www/test
            - ./logs/nginx:/var/log/nginx/
        working_dir: /var/www/test
networks:
    takeoff-network:
        driver: bridge
