import 'modules/common/layout/components/footer';
import 'modules/common/layout/components/header';
import 'modules/common/layout/components/layout';
import 'modules/pages/home/description';
import 'modules/pages/home/description-short';
import 'modules/pages/home/download-app';
import 'modules/pages/home/products';
import 'modules/pages/home/summary';
import './index.less';
